name: Build and Deploy
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: |
          cd src
          chmod +x gradlew
          ./gradlew make makePluginsJson

      - name: Push to builds branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: builds
          FOLDER: src/build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: ({sha}) {msg}"

